export const ProductInfoURL = "https://api.roblox.com/marketplace/productinfo"
export const CatalogSearchURL = "https://catalog.roblox.com/v1/search/items/details?"
export enum Category  {
        AllItems = 1,
        Clothing = 3,
        BodyParts = 4,
        Gear = 5,
        Accessories = 11,
        Animations = 12,
        Characters = 17,
}

export enum Subcategory  {
        Clothing = 3,
        BodyParts = 4,
        Gear = 5,
        Hats = 9,
        Faces = 10,
        Shirts = 12,
        TShirts = 13,
        Pants = 14,
        Heads = 15,
        Accessories = 19,
        HairAccessories = 20,
        FaceAccessories = 21,
        NeckAccessories = 22,
        ShoulderAccessories = 23,
        FrontAccessories = 24,
        BackAccessories = 25,
        WaistAccessories = 26,
        AvatarAnimations = 27,
        Bundles = 37,
        AnimationBundles = 38,
        EmoteAnimations = 39,
        CommunityCreations = 40,
        Melee = 41,
        Ranged = 42,
        Explosive = 43,
        PowerUp = 44,
        Navigation = 45,
        Musical = 46,
        Social = 47,
        Building = 48,
        Transport = 49,
}

export interface Asset {
        "id": number,
        "itemType": string,
        "assetType": number,
        "name": string,
        "description": string,
        "productId": number,
        "genres": string[],
        "itemStatus": [],
        "itemRestrictions": [],
        "creatorHasVerifiedBadge": boolean,
        "creatorType": string,
        "creatorTargetId": number,
        "creatorName": string,
        "price": number,
        "favoriteCount": boolean,
        "offSaleDeadline": Date
}